version: '3'

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "backend.celery_config", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "backend.celery_config", "beat", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_flower:
    build: .
    container_name: celery_flower
    command: ["celery", "-A", "backend.celery_config", "flower", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

networks:
  app_network:
    driver: bridge
