version: '3'

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "celery_config.app", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_APP=celery_config.app
      - CELERY_BROKER=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "celery_config.app", "beat", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_APP=celery_config.app
      - CELERY_BROKER=redis://redis:6379/0

networks:
  app_network:
    driver: bridge
